title: The Neuroscience of Data Science
logo: /Users/ashley/Documents/NeuralDataScience.github.io/brainz.jpeg
author: Ashley Juavinett & Bradley Voytek
only_build_toc_files: true
repository:
  url: https://github.com/NeuralDataScience/NeuralDataScience.github.io
  branch: master
launch_buttons: 
  colab_url: "https://colab.research.google.com"
