title: A Hands-On Guide to Neural Data Science
logo: /Users/VictorMagdaleno/NeuralDataScience.github.io/brainz.jpeg
author: Victor Magdaleno-Garcia
only_build_toc_files: true
repository:
  url: https://github.com/NeuralDataScience/NeuralDataScience.github.io
  branch: master
launch_buttons: 
  colab_url: "https://colab.research.google.com"